#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Compute the installation prefix relative to this file.
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
GET_FILENAME_COMPONENT(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

# Import target "vtksys" for configuration "Release"
SET_PROPERTY(TARGET vtksys APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtksys PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "dl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtksys.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtksys.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtksys )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtksys "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtksys.so.5.10.1" )

# Import target "vtkzlib" for configuration "Release"
SET_PROPERTY(TARGET vtkzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkzlib PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkzlib.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkzlib.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkzlib )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkzlib "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkzlib.so.5.10.1" )

# Import target "vtkhdf5" for configuration "Release"
SET_PROPERTY(TARGET vtkhdf5 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkhdf5 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m;vtkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkhdf5.so.1.8.5"
  IMPORTED_SONAME_RELEASE "libvtkhdf5.so.1.8.5"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkhdf5 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkhdf5 "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkhdf5.so.1.8.5" )

# Import target "vtkhdf5_hl" for configuration "Release"
SET_PROPERTY(TARGET vtkhdf5_hl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkhdf5_hl PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkhdf5"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkhdf5_hl.so.1.8.5"
  IMPORTED_SONAME_RELEASE "libvtkhdf5_hl.so.1.8.5"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkhdf5_hl )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkhdf5_hl "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkhdf5_hl.so.1.8.5" )

# Import target "vtkjpeg" for configuration "Release"
SET_PROPERTY(TARGET vtkjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkjpeg PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkjpeg.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkjpeg.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkjpeg )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkjpeg "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkjpeg.so.5.10.1" )

# Import target "vtkpng" for configuration "Release"
SET_PROPERTY(TARGET vtkpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;-lm"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkpng.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkpng.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkpng )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkpng "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkpng.so.5.10.1" )

# Import target "vtktiff" for configuration "Release"
SET_PROPERTY(TARGET vtktiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtktiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;vtkjpeg;-lm"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtktiff.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtktiff.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtktiff )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtktiff "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtktiff.so.5.10.1" )

# Import target "vtkexpat" for configuration "Release"
SET_PROPERTY(TARGET vtkexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkexpat PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkexpat.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkexpat.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkexpat )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkexpat "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkexpat.so.5.10.1" )

# Import target "vtkfreetype" for configuration "Release"
SET_PROPERTY(TARGET vtkfreetype APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkfreetype PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkfreetype.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkfreetype.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkfreetype )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkfreetype "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkfreetype.so.5.10.1" )

# Import target "vtklibxml2" for configuration "Release"
SET_PROPERTY(TARGET vtklibxml2 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtklibxml2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib;dl;-lpthread;dl;m"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtklibxml2.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtklibxml2.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtklibxml2 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtklibxml2 "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtklibxml2.so.5.10.1" )

# Import target "vtkDICOMParser" for configuration "Release"
SET_PROPERTY(TARGET vtkDICOMParser APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkDICOMParser PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkDICOMParser.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkDICOMParser.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkDICOMParser )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkDICOMParser "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkDICOMParser.so.5.10.1" )

# Import target "vtkproj4" for configuration "Release"
SET_PROPERTY(TARGET vtkproj4 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkproj4 PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "m"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkproj4.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkproj4.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkproj4 )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkproj4 "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkproj4.so.5.10.1" )

# Import target "mpistubs" for configuration "Release"
SET_PROPERTY(TARGET mpistubs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(mpistubs PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libmpistubs.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libmpistubs.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS mpistubs )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_mpistubs "${_IMPORT_PREFIX}/lib/vtk-5.10/libmpistubs.so.5.10.1" )

# Import target "MapReduceMPI" for configuration "Release"
SET_PROPERTY(TARGET MapReduceMPI APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(MapReduceMPI PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "mpistubs"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libMapReduceMPI.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libMapReduceMPI.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS MapReduceMPI )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_MapReduceMPI "${_IMPORT_PREFIX}/lib/vtk-5.10/libMapReduceMPI.so.5.10.1" )

# Import target "vtkverdict" for configuration "Release"
SET_PROPERTY(TARGET vtkverdict APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkverdict PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkverdict.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkverdict.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkverdict )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkverdict "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkverdict.so.5.10.1" )

# Import target "vtkNetCDF" for configuration "Release"
SET_PROPERTY(TARGET vtkNetCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkNetCDF PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkhdf5;vtkhdf5_hl"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkNetCDF.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkNetCDF.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkNetCDF )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkNetCDF "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkNetCDF.so.5.10.1" )

# Import target "vtkNetCDF_cxx" for configuration "Release"
SET_PROPERTY(TARGET vtkNetCDF_cxx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkNetCDF_cxx PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkNetCDF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkNetCDF_cxx.so"
  IMPORTED_SONAME_RELEASE "libvtkNetCDF_cxx.so"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkNetCDF_cxx )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkNetCDF_cxx "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkNetCDF_cxx.so" )

# Import target "vtkmetaio" for configuration "Release"
SET_PROPERTY(TARGET vtkmetaio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkmetaio PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkzlib"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkmetaio.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkmetaio.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkmetaio )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkmetaio "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkmetaio.so.5.10.1" )

# Import target "vtksqlite" for configuration "Release"
SET_PROPERTY(TARGET vtksqlite APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtksqlite PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "-lpthread"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtksqlite.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtksqlite.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtksqlite )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtksqlite "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtksqlite.so.5.10.1" )

# Import target "vtkexoIIc" for configuration "Release"
SET_PROPERTY(TARGET vtkexoIIc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkexoIIc PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkNetCDF"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkexoIIc.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkexoIIc.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkexoIIc )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkexoIIc "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkexoIIc.so.5.10.1" )

# Import target "LSDyna" for configuration "Release"
SET_PROPERTY(TARGET LSDyna APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(LSDyna PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libLSDyna.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libLSDyna.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS LSDyna )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_LSDyna "${_IMPORT_PREFIX}/lib/vtk-5.10/libLSDyna.so.5.10.1" )

# Import target "vtkalglib" for configuration "Release"
SET_PROPERTY(TARGET vtkalglib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkalglib PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkalglib.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkalglib.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkalglib )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkalglib "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkalglib.so.5.10.1" )

# Import target "vtkEncodeString" for configuration "Release"
SET_PROPERTY(TARGET vtkEncodeString APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkEncodeString PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/bin/vtkEncodeString"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkEncodeString )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkEncodeString "${_IMPORT_PREFIX}/bin/vtkEncodeString" )

# Import target "vtkftgl" for configuration "Release"
SET_PROPERTY(TARGET vtkftgl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkftgl PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/x86_64-linux-gnu/libGL.so;vtkfreetype"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkftgl.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkftgl.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkftgl )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkftgl "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkftgl.so.5.10.1" )

# Import target "vtkCommon" for configuration "Release"
SET_PROPERTY(TARGET vtkCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkCommon PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtksys;-lm"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkCommon.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkCommon.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkCommon )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkCommon "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkCommon.so.5.10.1" )

# Import target "vtkFiltering" for configuration "Release"
SET_PROPERTY(TARGET vtkFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkCommon"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkFiltering.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkFiltering.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkFiltering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkFiltering "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkFiltering.so.5.10.1" )

# Import target "vtkImaging" for configuration "Release"
SET_PROPERTY(TARGET vtkImaging APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkImaging PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkImaging.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkImaging.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkImaging )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkImaging "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkImaging.so.5.10.1" )

# Import target "vtkGraphics" for configuration "Release"
SET_PROPERTY(TARGET vtkGraphics APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGraphics PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkverdict"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGraphics.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkGraphics.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGraphics )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGraphics "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGraphics.so.5.10.1" )

# Import target "vtkGenericFiltering" for configuration "Release"
SET_PROPERTY(TARGET vtkGenericFiltering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGenericFiltering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering;vtkGraphics"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGenericFiltering.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkGenericFiltering.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGenericFiltering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGenericFiltering "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGenericFiltering.so.5.10.1" )

# Import target "vtkIO" for configuration "Release"
SET_PROPERTY(TARGET vtkIO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkIO PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkDICOMParser;vtkNetCDF;vtkNetCDF_cxx;LSDyna;vtkmetaio;vtksqlite;vtkpng;vtkzlib;vtkjpeg;vtktiff;vtkexpat;vtksys"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkFiltering"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkIO.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkIO.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkIO )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkIO "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkIO.so.5.10.1" )

# Import target "vtkRendering" for configuration "Release"
SET_PROPERTY(TARGET vtkRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkRendering PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkIO;vtkftgl;vtkfreetype"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkGraphics;vtkImaging"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkRendering.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkRendering.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkRendering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkRendering "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkRendering.so.5.10.1" )

# Import target "vtkVolumeRendering" for configuration "Release"
SET_PROPERTY(TARGET vtkVolumeRendering APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkVolumeRendering PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkIO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkVolumeRendering.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkVolumeRendering.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkVolumeRendering )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkVolumeRendering "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkVolumeRendering.so.5.10.1" )

# Import target "vtkHybrid" for configuration "Release"
SET_PROPERTY(TARGET vtkHybrid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkHybrid PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkexoIIc;vtkftgl"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkIO"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkHybrid.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkHybrid.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkHybrid )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkHybrid "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkHybrid.so.5.10.1" )

# Import target "vtkWidgets" for configuration "Release"
SET_PROPERTY(TARGET vtkWidgets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkWidgets PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkRendering;vtkHybrid;vtkVolumeRendering"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkWidgets.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkWidgets.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkWidgets )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkWidgets "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkWidgets.so.5.10.1" )

# Import target "vtkInfovis" for configuration "Release"
SET_PROPERTY(TARGET vtkInfovis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkInfovis PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtklibxml2;vtkalglib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkWidgets"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkInfovis.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkInfovis.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkInfovis )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkInfovis "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkInfovis.so.5.10.1" )

# Import target "vtkGeovis" for configuration "Release"
SET_PROPERTY(TARGET vtkGeovis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkGeovis PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkproj4"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkWidgets;vtkViews"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGeovis.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkGeovis.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkGeovis )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkGeovis "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkGeovis.so.5.10.1" )

# Import target "vtkViews" for configuration "Release"
SET_PROPERTY(TARGET vtkViews APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkViews PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkInfovis"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkViews.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkViews.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkViews )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkViews "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkViews.so.5.10.1" )

# Import target "QVTK" for configuration "Release"
SET_PROPERTY(TARGET QVTK APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(QVTK PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "/usr/lib/x86_64-linux-gnu/libQtWebKit.so;/usr/lib/x86_64-linux-gnu/libQtXmlPatterns.so;/usr/lib/x86_64-linux-gnu/libQtGui.so;/usr/lib/x86_64-linux-gnu/libQtSql.so;/usr/lib/x86_64-linux-gnu/libQtNetwork.so;/usr/lib/x86_64-linux-gnu/libQtCore.so;vtkRendering;vtkIO;vtkGraphics;vtkImaging;vtkCommon;vtkViews;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libQVTK.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libQVTK.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS QVTK )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_QVTK "${_IMPORT_PREFIX}/lib/vtk-5.10/libQVTK.so.5.10.1" )

# Import target "vtkCharts" for configuration "Release"
SET_PROPERTY(TARGET vtkCharts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(vtkCharts PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "vtkftgl"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "vtkViews"
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkCharts.so.5.10.1"
  IMPORTED_SONAME_RELEASE "libvtkCharts.so.5.10"
  )

LIST(APPEND _IMPORT_CHECK_TARGETS vtkCharts )
LIST(APPEND _IMPORT_CHECK_FILES_FOR_vtkCharts "${_IMPORT_PREFIX}/lib/vtk-5.10/libvtkCharts.so.5.10.1" )

# Loop over all imported files and verify that they actually exist
FOREACH(target ${_IMPORT_CHECK_TARGETS} )
  FOREACH(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    IF(NOT EXISTS "${file}" )
      MESSAGE(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    ENDIF()
  ENDFOREACH()
  UNSET(_IMPORT_CHECK_FILES_FOR_${target})
ENDFOREACH()
UNSET(_IMPORT_CHECK_TARGETS)

# Cleanup temporary variables.
SET(_IMPORT_PREFIX)

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
